# Generated by Django 2.1.3 on 2018-12-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='telephone',
            field=models.CharField(default='+380', max_length=20),
            preserve_default=False,
        ),
    ]
