# Generated by Django 2.1.3 on 2018-12-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0002_category_category_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Good',
        ),
    ]
