# Generated by Django 2.1.3 on 2018-12-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0003_auto_20181212_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
